### ISSUE TITLE
Separate bindings and binder responsibilities

### ISSUE THREAD

**Issue by Greg-Freeman** [illuminated-g/lv-propertybinding#2]
@negentropicdev just moving our conversation out of the old pull request since it's more of a design discussion.

For reference: 
What about something like this?

![image](https://github.com/illuminated-g/lv-propertybinding/assets/5956516/ea2a3e68-aa72-48ce-9527-8fc7b56f2648)

You could argue maybe it doesn't need to be in the library, and the library provides the necessary framework for someone to create it on their own like I just did. But it may be useful enough to include and kind of separates the responsibility of the binding definition into one class and then the execution of the binding into another class, the Binder.

**Comment by negentropicdev** [comment]
I almost did something like this. The question is what would an application using this look like? My thought was to keep the source and sinks separated so the code can decide at the time of transfer what classes are the source and sink. Then again I'm thinking of my use-cases and not yours. Since this is just composed behavior on top of the base implementation I've got no problem adding specialized optional layers.

Following the idea of a multi-binding wrapper I'd eliminate the intermediate cluster step; just call add binding twice with separate sink/source inputs. No need for the for loop and the intermediate type. Could call it MultiBinding or somesuch as a convenience layer over the existing single Binding. Otherwise if you'd like to stick with creating the array of bindings then they're all already wrapped into a single wire and there's not much need for the class itself and there could be just the method call. I'm definitely in favor of the class wrapper though and eliminating the details of the array structure from the calling code.

**Comment by negentropicdev** [comment]
@Greg-Freeman Yay? Nay?
![image](https://github.com/illuminated-g/lv-propertybinding/assets/59840835/8eedcbe2-9ff6-41ad-9a79-e2de04b82fbe)

**Comment by negentropicdev** [comment]
More differentiation
![image](https://github.com/illuminated-g/lv-propertybinding/assets/59840835/aa346e96-9f20-4181-be3b-04c6166a2243)

**Comment by Greg-Freeman** [comment]
@negentropicdev same idea, that should work.

The only thing that's a little tricky, and I think would be easier if we had native by-ref objects, is keeping the bindings with their associated object instances. It would be pretty easy to have a list of bindings and then wire up the wrong object type to the transfer methods as-is now.

If they were by-ref objects you could contain the _actual_ instance of the class with its associated bindings at construction time, so when you call transfer they'd all be encapsulated together already. i.e. these bindings go with this specific object I have created. But LabVIEW objects being by value, as soon as you branch the class wire to group it with the bindings, you've got a new object. So, with LabVIEW being a by value language, I think what you've got is probably the best option for that. 

Thoughts?

**Comment by negentropicdev** [comment]
It sounds like what you're really driving towards is a centralized value / variable table. You're saying stuff like operations (square a number) but treating it as a data sink. This binding, and LabVIEW being by-value, is definitely limited in its use cases but there's definitely more "LabVIEW" ways to accomplish stuff like this that reduced the need for by-reference objects.

Ultimately it sounds like your data and operation objects should be more integrated with the engine you're building. You can still configure data sources and sinks at run-time with various other means but 2ms per transfer and reliance on VI Server will relatively quickly hit a brick wall.

**Comment by negentropicdev** [comment]
For something like this I'd rather have a limited set of data types to handle and handle them explicitly with DD. (e.g. Double, Integer, Bool, String) or even with common read/write methods through variants. All of that will run 100 times faster than this approach.

**Comment by Greg-Freeman** [comment]
@negentropicdev agreed which is ultimately why I went with a centralized value table in the form of a map for my solution. Each class supplies the names of the properties it publishes via a must override VI. These can be used to register.

There is another must override called PopulateValueTable that classes can override to populate the value table. 

Following classes can pick off that.

This was more an exercise in "another way to do this" that I was curious about.
